const figures = {'gun': [
[ false, false, false, false, true, true, false, false, false, ],
[ false, false, false, false, true, true, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, true, true, true, false, false, ],
[ false, false, false, true, false, false, false, true, false, ],
[ false, false, true, false, false, false, false, false, true, ],
[ false, false, true, false, false, false, false, false, true, ],
[ false, false, false, false, false, true, false, false, false, ],
[ false, false, false, true, false, false, false, true, false, ],
[ false, false, false, false, true, true, true, false, false, ],
[ false, false, false, false, false, true, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, true, true, true, false, false, false, false, ],
[ false, false, true, true, true, false, false, false, false, ],
[ false, true, false, false, false, true, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ true, true, false, false, false, true, true, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, ],
[ false, false, true, true, false, false, false, false, false, ],
[ false, false, true, true, false, false, false, false, false, ],
],

'blinker': [
[ false, false, false, ],
[ true, true, true, ],
[ false, false, false, ],
],

'pulsar': [
[ false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, ],
[ false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, ],
[ false, false, false, false, true, true, false, false, false, true, true, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
[ true, true, true, false, false, true, true, false, true, true, false, false, true, true, true, ],
[ false, false, true, false, true, false, true, false, true, false, true, false, true, false, false, ],
[ false, false, false, false, true, true, false, false, false, true, true, false, false, false, false, ],
[ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, true, true, false, false, false, true, true, false, false, false, false, ],
[ false, false, true, false, true, false, true, false, true, false, true, false, true, false, false, ],
[ true, true, true, false, false, true, true, false, true, true, false, false, true, true, true, ],
[ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, ],
[ false, false, false, false, true, true, false, false, false, true, true, false, false, false, false, ],
[ false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, ],
[ false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, ],
],

'gllider': [
[ true, false, true, ],
[ false, true, true, ],
[ false, true, false, ],
],

'beacon': [
[ true, true, false, false, ],
[ true, true, false, false, ],
[ false, false, true, true, ],
[ false, false, true, true, ],
],

'lw_space_ship': [
[ false, true, true, false, ],
[ true, true, true, false, ],
[ true, true, false, true, ],
[ false, true, true, true, ],
[ false, false, true, false, ],
],

'toad': [
[ false, true, true, false, ],
[ false, false, false, true, ],
[ true, false, false, false, ],
[ false, true, true, false, ],
],

};